### ISSUE TITLE
Bundle as many things in one Java Runtime to prevent wasted memory usage

### ISSUE THREAD

**Issue by Kyrotechnic** [Swofty-Developments/HypixelSkyBlock#117]
Loading each service, the proxy, and servers is very innefficient on multiple Java Runtimes, as it uses more memory than bundling it in one Jar.

**Comment by Swofty-Developments** [comment]
Theoretically the project is made to scale, the proxy needs to be a separate plugin for Velocity, that can't be bundled. The concurrency issues that would occur with a decentralized service system with each of them running on all the servers would be an absolute mess, instead of say 300MB of ram on all 100 game nodes, we just have 300MB on one (a simplification but it gets the point across). 

In terms of having split game servers - At some point there also will be a player cap for the Minestom servers, say they can take up to 100 players each, what happens when we have player 101 log in? Do we sacrifice performance and go below 20TPS for the purpose of not bundling JVM runtimes? SkyBlock is also very intensive on its own, for one server to have all the dragon fights, auction house, crystal hallows, would kill the servers. [With the TypeLoader system we are able to load island-specific modules such as the Island types MinionHandler](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/a331c324e5f62071de090c65124d9fb620ef731b/type-island/src/main/java/net/swofty/type/island/TypeIslandLoader.java#L41).

**Comment by Kyrotechnic** [comment]
Also, I'm working on porting a scalable abstracted implementation of this into C#, as it has a lot better memory usage, better performance (in some cases), and is portable too.

**Comment by Swofty-Developments** [comment]
> Sorry, I know my Issue wasn't very descriptive. Bundling Services together in a Jar Loader would be more effective. Obviously bundling game servers would kill performance. However, we should look into methods of using seperate threads, to host multiple game servers on one runtime. Example: Have an instance run 5 different hub lobbies on 5 different threads, with the main data of the lobby being only defined once in the main instance manager. So the world data is only mapped in one instance. Also, optimizing Chunk Storage Data would be a good idea.

I see, this makes alot more sense however the entire codebase would have to be reimagined for it to work as stated. Concurrency would be a massive issue, even moreso than it already is when working with long-form requests like Islands and Auctions.

> Also, I'm working on porting a scalable abstracted implementation of this into C#, as it has a lot better memory usage, better performance (in some cases), and is portable too. [here](https://github.com/Kyrotechnic/HypixelSkyBlock)

I wish you the best, it won't be easy for sure. You'd have to completely recode the server software (Minestom) and then all of the Java code that I've added ontop.

**Comment by Kyrotechnic** [comment]
> I wish you the best, it won't be easy for sure. You'd have to completely recode the server software (Minestom) and then all of the Java code that I've added ontop.

It won't be as hard as you imagine. Rather than using an implementation of Minestom or remaking it, I'm making an abstract code base for Packets. Other than that, it won't be too hard. You can implement Protocols by extending IProtocol and registering the ProtocolInfo.cs class and then registering functions as Packet Ids and Packet Modes. The protocol implementation is the easiest part.

> I see, this makes alot more sense however the entire codebase would have to be reimagined for it to work as stated. Concurrency would be a massive issue, even moreso than it already is when working with long-form requests like Islands and Auctions.

Yes, that is true. However, you only have to manage things such as chunkdata on the main thread. Read shouldn't be a problem, concurrency is only a problem on write. And with multi threading, it adds the ability to have a lot more players on one server.
